name: Collect Jobs

on:
 schedule:
   - cron: '* 6 * * *'

jobs:
  collect-jobs:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Setup The Php Website
      run: |
        composer install && yarn install && rm source/*/.gitkeep

    - name: Build
      run: ./vendor/bin/jigsaw build production && rm -rf ./build_production/

    - name: Commit Changes
      run: |
       git config --local user.email "action@github.com"
       git config --local user.name "GitHub Action"
       git add ./source/_jobs_pt_br/
       git commit -m "Update jobs inventory"

    - name: Store Jobs
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        repository: nawarian/The-PHP-Website

