name: github pages

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Setup The Php Website
      run: composer install && yarn install

    - name: Quality Gate
      run: ./vendor/bin/phpunit -c phpunit.xml

    - name: Build
      run: ./vendor/bin/jigsaw build production

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build_production
    - name: Ping Search Engines
      run: bash ./scripts/ping-search-engines.sh

